

import { Event } from '@/types'

export const sampleEvents: Event[] = [
  {
    id: '1',
    title: 'Google Summer of Code 2025',
    description: 'A global program focused on bringing student developers into open source software development.',
    type: 'internship',
    platform: 'unstop',
    url: 'https://unstop.com/hackathons/google-summer-of-code-2025-1256789',
    deadline: '2025-04-02',
    location: 'remote',
    eligibility: ['undergraduate', 'graduate'],
    tags: ['open-source', 'google', 'programming', 'mentorship'],
    isActive: true,
    createdAt: '2025-01-15'
  },
  {
    id: '2',
    title: 'Microsoft Engage 2025 Mentorship Program',
    description: 'Exclusive mentorship program for engineering students with Microsoft experts.',
    type: 'internship',
    platform: 'unstop',
    url: 'https://unstop.com/internships/microsoft-engage-2025-1256790',
    deadline: '2025-03-15',
    location: 'remote',
    eligibility: ['undergraduate'],
    tags: ['microsoft', 'mentorship', 'engineering', 'career-growth'],
    isActive: true,
    createdAt: '2025-01-20'
  },
  {
    id: '3',
    title: 'Flipkart Runway Season 4 - Women in Tech',
    description: 'Exclusive hiring challenge for women engineers across India with PPO opportunities.',
    type: 'coding_challenge',
    platform: 'hackerrank',
    url: 'https://www.hackerrank.com/flipkart-runway-2025',
    deadline: '2025-02-28',
    location: 'remote',
    eligibility: ['undergraduate', 'graduate'],
    tags: ['flipkart', 'women-in-tech', 'hiring', 'coding'],
    isActive: true,
    createdAt: '2025-01-10'
  },
  {
    id: '4',
    title: 'Amazon ML Summer School 2025',
    description: 'Learn machine learning from Amazon scientists with certificate and internship opportunities.',
    type: 'workshop',
    platform: 'unstop',
    url: 'https://unstop.com/workshops/amazon-ml-summer-school-2025-1256791',
    deadline: '2025-03-20',
    location: 'remote',
    eligibility: ['undergraduate'],
    tags: ['amazon', 'machine-learning', 'ai', 'workshop'],
    isActive: true,
    createdAt: '2025-01-25'
  },
  {
    id: '5',
    title: 'JP Morgan Code for Good 2025',
    description: '24-hour hackathon to solve challenges for non-profit organizations with full-time opportunities.',
    type: 'hackathon',
    platform: 'hackerrank',
    url: 'https://www.hackerrank.com/jpmorgan-code-for-good-2025',
    deadline: '2025-03-10',
    location: 'hybrid',
    eligibility: ['undergraduate', 'graduate'],
    tags: ['jp-morgan', 'finance', 'coding', 'social-impact'],
    isActive: true,
    createdAt: '2025-01-18'
  },
  {
    id: '6',
    title: 'Goldman Sachs Engineering Campus Hiring',
    description: 'Coding challenge for 2025 batch students with opportunities for summer internships.',
    type: 'coding_challenge',
    platform: 'hackerrank',
    url: 'https://www.hackerrank.com/goldman-sachs-2025',
    deadline: '2025-02-25',
    location: 'remote',
    eligibility: ['undergraduate'],
    tags: ['goldman-sachs', 'engineering', 'hiring', 'finance'],
    isActive: true,
    createdAt: '2025-01-12'
  },
  {
    id: '7',
    title: 'Intuit Augment 2025 - Product Development',
    description: 'Product development challenge with mentorship from Intuit leaders.',
    type: 'hackathon',
    platform: 'other',
    url: 'https://devfolio.co/hackathons/intuit-augment-2025',
    deadline: '2025-04-05',
    location: 'remote',
    eligibility: ['undergraduate', 'graduate'],
    tags: ['intuit', 'product-development', 'fintech', 'innovation'],
    isActive: true,
    createdAt: '2025-01-30'
  },
  {
    id: '8',
    title: 'Salesforce Developer Virtual Internship',
    description: 'Hands-on virtual internship to learn Salesforce development with real projects.',
    type: 'internship',
    platform: 'internshala',
    url: 'https://internshala.com/internship/salesforce-developer-virtual-internship-1256792',
    deadline: '2025-03-30',
    location: 'remote',
    eligibility: ['undergraduate', 'graduate'],
    tags: ['salesforce', 'crm', 'development', 'virtual'],
    isActive: true,
    createdAt: '2025-01-22'
  },
  {
    id: '9',
    title: 'Adobe Women-in-Tech Scholarship 2025',
    description: 'Scholarship and mentorship program for women students pursuing technology careers.',
    type: 'workshop',
    platform: 'unstop',
    url: 'https://unstop.com/scholarships/adobe-women-in-tech-2025-1256793',
    deadline: '2025-04-15',
    location: 'remote',
    eligibility: ['undergraduate', 'graduate'],
    tags: ['adobe', 'women-in-tech', 'scholarship', 'design'],
    isActive: true,
    createdAt: '2025-01-28'
  },
  {
    id: '10',
    title: 'TCS CodeVita Season 12',
    description: 'Worlds largest coding contest by TCS with prizes and job opportunities.',
    type: 'coding_challenge',
    platform: 'hackerrank',
    url: 'https://www.hackerrank.com/tcs-codevita-2025',
    deadline: '2025-03-25',
    location: 'remote',
    eligibility: ['undergraduate', 'graduate'],
    tags: ['tcs', 'coding', 'competition', 'career'],
    isActive: true,
    createdAt: '2025-01-15'
  },
  {
    id: '11',
    title: 'Walmart Global Tech Hackathon 2025',
    description: 'Build innovative retail tech solutions with Walmart experts and win exciting prizes.',
    type: 'hackathon',
    platform: 'other',
    url: 'https://devfolio.co/hackathons/walmart-tech-2025',
    deadline: '2025-04-20',
    location: 'hybrid',
    eligibility: ['undergraduate', 'graduate', 'professional'],
    tags: ['walmart', 'retail-tech', 'innovation', 'shopping'],
    isActive: true,
    createdAt: '2025-02-01'
  },
  {
    id: '12',
    title: 'Morgan Stanley Code to Give 2025',
    description: 'Hackathon focused on creating technology solutions for social good organizations.',
    type: 'hackathon',
    platform: 'hackerrank',
    url: 'https://www.hackerrank.com/morgan-stanley-code-to-give-2025',
    deadline: '2025-04-10',
    location: 'remote',
    eligibility: ['undergraduate', 'graduate'],
    tags: ['morgan-stanley', 'social-good', 'finance', 'coding'],
    isActive: true,
    createdAt: '2025-01-26'
  }
]
